# Generated by Django 4.1 on 2022-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calenderapp', '0002_alter_calender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('R', 'red'), ('B', 'blue'), ('G', 'green'), ('Y', 'yellow')], max_length=1)),
                ('state', models.CharField(choices=[(1, 'on'), (0, 'off')], default=0, max_length=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calenderapp.calender')),
            ],
        ),
    ]
