# Generated by Django 4.1 on 2022-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledapp', '0002_alter_led_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='state',
            field=models.CharField(choices=[('1', 'on'), ('0', 'off')], default=0, max_length=1),
        ),
    ]
